In [9]:
import pandas as pd

emissions = pd.read_csv("https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert")
emissions.head(20)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219
8,01010,ANGLEFORT,1070.411510,143.815664,NaN,1286.621447,146.525382,341.410872,175185.892467,448.518801,3199.808360,1206.147643
9,01011,APREMONT,2010.790441,NaN,NaN,249.086914,52.103791,2.354558,6.911213,151.844891,686.153720,188.542701
10,01012,ARANC,1226.155903,NaN,NaN,337.555027,41.524341,42.382039,124.401840,126.369566,934.984677,150.259919
11,01013,ARANDAS,1640.331757,NaN,NaN,130.878322,20.894414,2.354558,6.911213,65.289246,394.310427,75.608494
12,01014,ARBENT,84.699485,153.038864,NaN,9320.284310,28.169819,2371.039645,6959.591844,4955.425444,13120.992480,4576.655612
13,01015,ARBOYS EN BUGEY,750.452098,NaN,NaN,430.926166,128.937801,16.481904,48.378493,247.719765,1545.025338,301.955443
14,01016,ARBIGNY,1659.900746,382.957621,22.094924,346.188954,56.467814,14.127346,41.467280,171.499783,993.374941,204.334349
15,01017,ARGIS,550.294711,79.782366,NaN,344.670004,55.806598,2.354558,6.911213,177.330667,2063.095873,1366.441253
16,01019,ARMIX,566.474446,NaN,NaN,30.571400,2.777106,2.354558,6.911213,9.607822,157.527852,10.049230
17,01021,ARS-SUR-FORMANS,962.444113,NaN,NaN,750.283619,183.421214,14.127346,41.467280,1592.980055,1268.202015,663.727733
18,01022,ARTEMARE,467.272140,21.920510,NaN,677.973789,155.385671,21.191020,62.200920,530.636818,1396.646646,562.278360
19,01023,ASNIERES-SUR-SAONE,1595.032852,93.343398,5.385492,81.100935,9.124776,2.354558,6.911213,28.283499,171.864555,33.018899

In [19]:
newdf = emissions.drop(columns = ["Agriculture", "CO2 biomasse hors-total", "Déchets", "Energie", "Industrie hors-énergie", "Résidentiel", "Routier", "Tertiaire"])
newdf.head(2)
newdf = newdf.rename(columns ={"INSEE commune" : "Code_INSEE", "Autres transports" : "Transport", "Autres transports international" : "Transport international"})

In [35]:
newdf.fillna(0, inplace = True)
newdf.head()

  Code_INSEE                  Commune   Transport  Transport international dep
0      01001  L'ABERGEMENT-CLEMENCIAT    0.000000                      0.0  01
1      01002    L'ABERGEMENT-DE-VAREY    0.000000                      0.0  01
2      01004        AMBERIEU-EN-BUGEY  212.577908                      0.0  01
3      01005      AMBERIEUX-EN-DOMBES    0.000000                      0.0  01
4      01006                  AMBLEON    0.000000                      0.0  01

In [37]:
newdf["dep"] = newdf["Code_INSEE"].astype(str).str[:2]
newdf["transports_total"] = newdf["Transport"] + newdf["Transport international"]
newdf

,Code_INSEE,Commune,Transport,Transport international,dep,transports_total
0,01001,L'ABERGEMENT-CLEMENCIAT,0.000000,0.0,01,0.000000
1,01002,L'ABERGEMENT-DE-VAREY,0.000000,0.0,01,0.000000
2,01004,AMBERIEU-EN-BUGEY,212.577908,0.0,01,212.577908
3,01005,AMBERIEUX-EN-DOMBES,0.000000,0.0,01,0.000000
4,01006,AMBLEON,0.000000,0.0,01,0.000000
...,...,...,...,...,...,...
35793,95676,VILLERS-EN-ARTHIES,0.000000,0.0,95,0.000000
35794,95678,VILLIERS-ADAM,0.000000,0.0,95,0.000000
35795,95680,VILLIERS-LE-BEL,0.000000,0.0,95,0.000000
35796,95682,VILLIERS-LE-SEC,0.000000,0.0,95,0.000000
35797,95690,WY-DIT-JOLI-VILLAGE,0.000000,0.0,95,0.000000

In [ ]:
newdf.sort_values("transports_total")

transoifrmer en entier : .astype(int)